#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## launch mako with alt config

CONFIG="$HOME/.config/mako/config"

if [[ ! `pidof mako` ]]; then
	mako --config ${CONFIG}
fi
