#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# General config
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config window_gap 10
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus off
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config split_ratio 0.5
yabai -m config auto_balance on
yabai -m config focus_follows_mouse autofocus

yabai -m config top_padding 40
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$"       manage=off
yabai -m rule --add app="^App Store$"        manage=off
yabai -m rule --add app="^Safari$"           manage=off
yabai -m rule --add app="^Preview$"          manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^balenaEtcher$"     manage=off
yabai -m rule --add app="^Archive Utility$"  manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off

# Optional: Start sketchybar (or borders) if you want
sketchybar &
borders active_color=0xfffab387 width=6.0 &
