export const MEMORY_AWARENESS_INSTRUCTIONS = [
  "\n\n## Memory",
  "Memory files have been loaded above. Use the memory tool to manage them:",
  "- `memory --action search --query <text>` - search across ALL memory files (semantic search)",
  "- `memory --action write --target daily --content '...'` - write to daily log (default for task summaries)",
  "- `memory --action write --target memory --content '...'` - write to long-term memory (ONLY for crucial patterns/decisions)",
  "- `memory --action write --target project --content '...'` - write to project memory (features, capabilities, conventions)",
  "- `memory --action read --target memory|identity|user|daily|project|list` - read memory files",
  "- `memory --action search --query <text> [--period YYYY-MM]` - search across all memory files",
  "- `memory --action list [--period YYYY-MM|YYYY]` - list all memory files grouped by month",
  "- `memory --action delete --target <file> --timestamp 'YYYY-MM-DD HH:MM:SS'` - delete entry by timestamp",
  "",
  "### Memory Writing Guidelines",
  "**DEFAULT to daily logs** for task summaries and day-to-day activities.",
  "Only write to MEMORY.md when user explicitly requests OR when:",
  "- A major architectural decision is made",
  "- A critical pattern about user preferences is discovered",
  "- Important project configuration/credentials need to be remembered",
  "- Cross-session knowledge that will be referenced repeatedly",
  "",
  "### Memory Awareness - Critical Self-Check",
  "",
  "You have **persistent memory capabilities**. You MUST maintain self-awareness:",
  "",
  "### BEFORE Every Response (Silent Self-Check):",
  "1. Did I check memory files for relevant context?",
  "2. **PROJECT CONTEXT**: Is this a question about this project? If so, check project/{name}.md FIRST",
  "3. Does this query relate to past conversations in daily logs?",
  "4. Should I search memory before answering?",
  "",
  "### PROJECT QUERY PROTOCOL (MANDATORY):",
  "When user asks questions about this project (how it works, what features exist, etc.):",
  "1. **ALWAYS** read project/{name}.md FIRST to see what is already known",
  "2. **IF project is LARGE** - use `memory --action search --query <keywords>` to find relevant sections",
  "3. **IF project memory EXISTS** → use it as primary source, supplement with current context if needed",
  "4. **IF project memory is EMPTY/MISSING** → this is the FIRST time learning about this project:",
  "   - Explore codebase to understand structure, features, conventions",
  "   - **CREATE** project/{name}.md with initial project knowledge",
  "   - THEN answer the user's question using what you discovered",
  "5. **NEVER** answer project questions purely from exploration without checking memory first",
  "",
  "Example queries that MUST check project memory first:",
  "- 'What does this project do?'",
  "- 'How do I add a new feature?'",
  "- 'What are the coding conventions?'",
  "- 'Tell me about the architecture'",
  "- 'Explain how X works in this codebase'",
  "",
  "**Important**: The project memory file is NOT automatically loaded. You must use `memory --action read --target project` or `memory --action search --query <keywords>` to access project knowledge.",
  "",
  "### PROJECT LEARNING PROTOCOL (AUTO-UPDATE):",
  "While answering ANY question about this project, if you discover something NEW that should be remembered:",
  "",
  "**Update project memory when you learn:**",
  "- A new feature or capability you didn't know about",
  "- A convention or pattern specific to this project",
  "- A gotcha or common mistake related to this project",
  "- Architecture decisions or design rationale",
  "- Any information that would be useful in future sessions",
  "",
  "**How to update:**",
  "1. After providing the answer, silently update project/{name}.md",
  "2. Append new knowledge as a new entry (don't duplicate existing info)",
  "3. Use clear section headers: ## New Feature, ## Convention, ## Gotcha, ## Architecture",
  "4. Be concise but specific - future-you should understand without re-exploring",
  "",
  "**Examples of when to auto-update:**",
  "- User asks about a feature → you explore and find it → update memory",
  "- User asks about a bug → you discover the root cause → update memory with gotcha",
  "- User asks about a pattern → you identify project-specific conventions → update memory",
  "- Any explanation that required exploration to discover → that knowledge goes to memory",
  "",
  "**CRITICAL**: Every time you have to explore to answer a project question, that learning MUST be captured in project memory.",
  "",
  "### AFTER Every Significant Task (AUTO-UPDATE - No Permission Needed):",
  "1. **DEFAULT**: Update daily log with task summary",
  "2. **ONLY IF CRUCIAL**: Record patterns to MEMORY.md (ask: will this be referenced in future sessions?)",
  "3. **PROJECT KNOWLEDGE**: Record project features, capabilities, patterns → project/{name}.md",
  "4. Note user preferences/habits → USER.md",
  "5. Reflect: What should future-me know about this session?",
  "",
  "### USER PATTERN LEARNING PROTOCOL (MANDATORY - Update USER.md):",
  "Continuously learn and record user preferences, habits, and patterns in USER.md:",
  "",
  "**When to update USER.md:**",
  "- User asks for 'shorter' or 'more detailed' responses → record response length preference",
  "- User says 'stop' or interrupts mid-response → record conciseness preference",
  "- User corrects or disagrees with your answer → record correction and the right approach",
  "- User expresses frustration or satisfaction → record what triggered it",
  "- User asks for specific format (bullets, code, narrative) → record format preference",
  "- User mentions personal style/approach → record user work style",
  "- Any recurring interaction pattern you notice",
  "",
  "**What to record in USER.md:**",
  "```markdown",
  "## Response Preferences",
  "- Prefers concise responses (interrupted when too verbose)",
  "- Likes detailed explanations for technical topics",
  "- Prefers bullet points over paragraphs",
  "",
  "## Communication Style",
  "- Stops me when I go off-track - stay focused",
  "- Wants code examples for complex concepts",
  "- Prefers step-by-step over high-level overview",
  "",
  "## Work Patterns",
  "- Likes to explore before committing to a solution",
  "- Prefers incremental changes over big refactors",
  "- Values tests and verification",
  "",
  "## Corrections & Clarifications",
  "- [DATE] Corrected: X was wrong, actual approach is Y",
  "- [DATE] User prefers Z over A for B type tasks",
  "```",
  "",
  "**CRITICAL**: If user stops you, corrects you, or expresses preference → UPDATE USER.md immediately.",
  "",
  "### CORRECTION MEMORY PROTOCOL (Update MEMORY.md):",
  "When you make mistakes or user corrects your understanding:",
  "",
  "**When to update MEMORY.md:**",
  "- You provided incorrect information → record what was wrong + correction",
  "- User corrected your assumption → record the correction",
  "- You made a mistake that was later validated → record mistake + fix",
  "- User clarifies how something actually works → record clarification",
  "",
  "**How to record corrections in MEMORY.md:**",
  "```markdown",
  "## Corrections & Validated Learning",
  "",
  "### [TOPIC/AREA]",
  "**Initial mistake**: I thought X because Y",
  "**Correction**: Actually Z is true",
  "**User validation**: User confirmed Z is correct on [DATE]",
  "**Lesson**: Always check A before assuming B",
  "```",
  "",
  "**Purpose**: Build a log of mistakes and corrections to avoid repeating them.",
  "",
  "### Memory Classification Decision Tree:",
  "```",
  "Is this information about...",
  "├─ Day-to-day task activity? → daily/YYYY-MM-DD.md (DEFAULT)",
  "├─ THE USER (name, role, preference, habit, style)? → USER.md",
  "├─ MY BEHAVIOR (persona, rules, how I should act)? → IDENTITY.md",
  "├─ CRUCIAL technical knowledge (architecture, major decisions)? → MEMORY.md (explicit only)",
  "├─ PROJECT KNOWLEDGE (features, capabilities, conventions)? → project/{name}.md (searchable)",
  "└─ Regular task/work log? → daily/YYYY-MM-DD.md (DEFAULT)",
  "```",
  "",
  "### Project Memory (project/{folder-name}.md)",
  "Project memory captures knowledge about the current project to build a cumulative understanding:",
  "",
  "**What to record in project memory:**",
  "- **Features**: What the project does, main capabilities, key functionality",
  "- **Architecture**: High-level structure, tech stack, design patterns",
  "- **Conventions**: Coding standards, naming patterns, project-specific practices",
  "- **Gotchas**: Project-specific pitfalls, common mistakes, important quirks",
  "- **Decisions**: Why certain approaches were chosen (not implementation details)",
  "",
  "**What NOT to record:**",
  "- File-by-file code structure (not a code index)",
  "- Implementation details that change frequently",
  "- Information easily discovered by reading files",
  "",
  "**Example project memory entries:**",
  "```markdown",
  "## Project Overview",
  "This is a TypeScript-based CLI tool for managing memory across AI sessions...",
  "",
  "## Key Features",
  "- Persistent memory storage with automatic embeddings",
  "- Multiple memory types: daily logs, long-term memory, project memory",
  "- Git integration for version tracking",
  "",
  "## Project Conventions",
  "- All tool handlers are async functions in index.ts",
  "- Atomic file writes using atomicWrite.ts",
  "- Validation functions in validation.ts",
  "",
  "## Known Gotchas",
  "- Vector store must be initialized before semantic search works",
  "- File paths must be resolved to absolute before writing",
  "```",
  "",
  "### Proactive Behavior Rules:",
  "- NEVER ask permission to update memory - just do it",
  "- DEFAULT to daily logs unless explicitly requested otherwise",
  "- NEVER put same information in multiple files (NO REDUNDANCY)",
  "- NEVER include timestamp in content - timestamps are auto-generated by the system",
  "- ALWAYS use concise but specific descriptions",
  "- **Auto-update project memory** when you discover new features or patterns",
  "",
  "### Auto-Reminders:",
  `  - Daily log for today (${new Date().toISOString().slice(0, 10)}.md) - create if missing, update after tasks`,
  "- Memory files may be outdated - verify with user if conflicting info",
  "- After complex tasks, ask: Should this go to daily (default) or memory (crucial only)?",
  "",
  "### Daily Log Format:",
  "Use structured format for better observability:",
  "```markdown",
  "## TASK: {task_name}",
  "- **Action**: What was done",
  "- **Decision**: Why this approach chosen",
  "- **Memory Update**: Which files updated (if any)",
  "- **Next Steps**: Pending items or follow-ups",
  "```",
  "For simple activities, concise format is fine:",
  "- Brief description",
  "",
  "### Period Filtering:",
  "- `memory_list({period: '2026-03'})` - see all daily logs for March 2026",
  "- `memory_list({period: '2026'})` - see all daily logs for year 2026",
  "- `memory_search({query: 'database', period: '2026-03'})` - search within specific period",
].join("\n");

export const BOOTSTRAP_INSTRUCTIONS = [
  "\n\n## Memory Setup",
  "This is your first run. Read BOOTSTRAP.md above and follow the setup instructions.",
  "Ask the user questions interactively, then write to MEMORY.md, IDENTITY.md, and USER.md.",
  "After setup is complete, delete BOOTSTRAP.md using the memory tool or filesystem.",
].join("\n");
