export GIT_FUZZY_SELECT_ALL_KEY="${GIT_FUZZY_SELECT_ALL_KEY:-Ctrl-A}"
export GIT_FUZZY_SELECT_NONE_KEY="${GIT_FUZZY_SELECT_NONE_KEY:-Ctrl-N}"

export GIT_FUZZY_STATUS_ADD_KEY="${GIT_FUZZY_STATUS_ADD_KEY:-Ctrl-G}"
export GIT_FUZZY_STATUS_ADD_PATCH_KEY="${GIT_FUZZY_STATUS_ADD_PATCH_KEY:-Ctrl-P}"
export GIT_FUZZY_STATUS_EDIT_KEY="${GIT_FUZZY_STATUS_EDIT_KEY:-Ctrl-O}"
export GIT_FUZZY_STATUS_COMMIT_KEY="${GIT_FUZZY_STATUS_COMMIT_KEY:-Ctrl-F}"
export GIT_FUZZY_STATUS_RESET_KEY="${GIT_FUZZY_STATUS_RESET_KEY:-Ctrl-R}"
export GIT_FUZZY_STATUS_DISCARD_KEY="${GIT_FUZZY_STATUS_DISCARD_KEY:-Ctrl-X}"
export GIT_FUZZY_STATUS_AMEND_KEY="${GIT_FUZZY_STATUS_AMEND_KEY:-Ctrl-B}"

export GF_LOG_MENU_PARAMS="${GF_LOG_MENU_PARAMS:---all --date=short --pretty=\"%C(cyan)%h%Creset %<(55,trunc)%s %C(green)%ad%Creset %C(yellow)%an%Creset\"}"
