#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Script for spotify for waybar

player_status=$(playerctl status 2> /dev/null)

if [ "$player_status" = "Playing" ]; then
    echo -e " $(playerctl metadata title) by $(playerctl metadata artist) \nPlaying: $(playerctl metadata artist) - $(playerctl metadata title)\nplaying" | sed 's/&/&amp;/g'
elif [ "$player_status" = "Paused" ]; then
    echo -e " $(playerctl metadata title) by $(playerctl metadata artist)\nPaused: $(playerctl metadata artist) - $(playerctl metadata title)\npaused" | sed 's/&/&amp;/g'
else
	echo -e ""
fi
